### ISSUE TITLE
Folders or branches?

### ISSUE THREAD

**Issue by elderamevans** [elderamevans/familysearch-gramps#4]
I'm now undecided:
Should we use folders, or branches, to separate each GRAMPS version?

I know I've set up branches, but I'm feeling that it may complicate things in the long run....

**Comment by sam-m888** [comment]
@elderamevans Git Branches for Gramps as you already have them.

**Comment by elderamevans** [comment]
Good point. If there's an absolute need to switch to folders, it shouldn't bee too hard.
